### PR TITLE
Deposit Adapter Contract

### PR DESCRIPTION
**Pull request by jtfirek**
- Allows for atomic swaps to weETH from {ETH, wETH, stETH, wstETH} 
- Original plan was to provide these features in a separate contracts without additions to our core contracts, but sadly this approach incorrectly populates the sender field of the deposit event which the growth team relies on. The functions added to liquifier and liquidity pool fix this

### CODE REVIEW

**Comment by solipsis** [comment]
If the blocker on your ideal solution is the transfer event, would it be better for us to just make a new event with with the sender field the growth team expects and they can just swap to the new event?

**Comment by jtfirek** [comment]
> If the blocker on your ideal solution is the transfer event, would it be better for us to just make a new event with with the sender field the growth team expects and they can just swap to the new event?

This is a good point! The points printer is already janky so this definitely a better solution that adding weird code to our core contracts

**Comment by jtfirek** [comment]
I updated the code using dave's suggestion. Now requires 0 changes to our core contracts!

**Review by seongyun-ko — APPROVED** [review]
LGTM

**Comment by Shivam78288** [comment]
You should check the amount of stETH that actually got transferred to the contract by taking the delta of before and after. A lot of times, the stETH amount transferred is 1 wei lesser and it may cause the tx to revert.

**Comment by jtfirek** [comment]
> You should check the amount of stETH that actually got transferred to the contract by taking the delta of before and after. A lot of times, the stETH amount transferred is 1 wei lesser and it may cause the tx to revert.

Yea I had to use `assertApproxEqAbs` quite a bit due to output amounts being 1-2 wei less than expected, but it doesn't seem to result in reverts due to the fact that stETH `transferFrom` is transferring shares under the hood.

I added an additional delta checks, but lmk if you were looking for something more specific!

**Comment by seongyun-ko** [comment]
An extension would be to allow deposit of ETH for {weETHs, weETHk}

**Pull request merged**
