### PR TITLE
fix the accounting error in dust share for withdrawal requests

### PR DESCRIPTION
**Pull request by seongyun-ko**
Handle https://github.com/etherfi-protocol/smart-contracts/issues/24

### CODE REVIEW

**Review by jtfirek — APPROVED** [review]

**Comment by jtfirek** [comment]
ltgm! My only question is can we redirect the fee to a more useful place than `membershipManager` or remove the fee all together at some point?

**Review by jtfirek — CHANGES_REQUESTED** [review]
We should remove the fee

**Review by jtfirek — COMMENTED** [review]
Should we go head and remove the ether.fi burn fee completely? This has been deprecated and jv has to periodically do manual refunds to users when they complain about this

**Comment by seongyun-ko** [comment]
> Should we go head and remove the ether.fan burn fee completely? We have told users there is no longer a burn fee and jv has to periodically send manual refunds to users when they complain about this
> 
> I can build off this PR if you want me to implement this.

we can update the fee https://etherscan.io/address/0x3d320286E014C3e1ce99Af6d6B00f0C1D63E3000#writeProxyContract#F13

**Pull request merged**
